### ISSUE TITLE
Google Sheet Export Bugs

### ISSUE THREAD

**Issue by jitendraag** [coronasafe/life#253]
**Describe the bug**
I am listing multiple bugs here because many of them might have the same fix.
- Currently the Google sheet export is very difficult to use (pain points below):

1. Order of columns in our Google sheet export is NOT same as sample data or data structure. If someone wants to use this Google sheet and copy paste data to their existing sheet, they can't do this without reordering columns first.
2. We are exposing internal fields like state_id, district_id, delete etc. These are not documented in our schema and are not part of our public schema. I am afraid if someone can mess up with our system if these ids are exposed. (Can we confirm these columns will be discarded)
3. I saw pincode and pin_code columns. We should remove pin_code
4. I also see columns that are NOT part of our schema but came from external partners. We should consider removing those from our output.
5. Order of columns and number of columns between all our sheets should be same (right now it's not)

**To Reproduce**
Try to combine data from 5 sheets [here](https://docs.google.com/spreadsheets/d/1Oyuf3LOjBr_ubJOJCTlBk6ODg3jXiSlLMW9g4-m5SHU/edit#gid=0
) into a sheet in our format that you are already working on:

**Expected behavior**
Explained above

**Screenshots**
NA

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by shrihari689** [comment]
Fixed 📍🚀 

1. Ordered according to Mandatory Fields ✅ 
2. Removed all internal fields ✅  But dumped `id`  column as `external_id`
3. It was from our spreadsheet data I think, because backend (`pincode`) has no issue. ✅ 
4. Somehow managed to show data as of our schema 📌 ✅ 
5. Done ✅ 

I also provided the schema on GitHub Issue comment. :pushpin:

🔴 Update: Our Master DB Spreadsheets has sheets according to category and also a Master sheet which contains all data 🎉 

cc: @bodhi @Vignesh
